<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
$mod_strings = array (
  'LBL_ASSIGNED_TO_ID' => 'Assigned User Id',
  'LBL_ASSIGNED_TO_NAME' => 'Assigned to',
  'LBL_ID' => 'ID',
  'LBL_DATE_ENTERED' => 'Date Created',
  'LBL_DATE_MODIFIED' => 'Date Modified',
  'LBL_MODIFIED' => 'Modified By',
  'LBL_MODIFIED_ID' => 'Modified By Id',
  'LBL_MODIFIED_NAME' => 'Modified By Name',
  'LBL_CREATED' => 'Created By',
  'LBL_CREATED_ID' => 'Created By Id',
  'LBL_DESCRIPTION' => 'Description',
  'LBL_DELETED' => 'Deleted',
  'LBL_NAME' => 'Name',
  'LBL_CREATED_USER' => 'Created by User',
  'LBL_MODIFIED_USER' => 'Modified by User',
  'LBL_LIST_NAME' => 'Name',
  'LBL_EDIT_BUTTON' => 'Edit',
  'LBL_REMOVE' => 'Remove',
  'LBL_NUMBER' => 'Number:',
  'LBL_STATUS' => 'Status:',
  'LBL_PRIORITY' => 'Priority:',
  'LBL_RESOLUTION' => 'Resolution',
  'LBL_LAST_MODIFIED' => 'Last Modified',
  'LBL_WORK_LOG' => 'Work Log:',
  'LBL_CREATED_BY' => 'Created by:',
  'LBL_DATE_CREATED' => 'Date Created:',
  'LBL_MODIFIED_BY' => 'Last Modified by:',
  'LBL_ASSIGNED_USER' => 'Assigned User:',
  'LBL_SYSTEM_ID' => 'System Id:',
  'LBL_TYPE' => 'Type:',
  'LBL_SUBJECT' => 'Name:',
  'LBL_LIST_FORM_TITLE' => 'Case File List',
  'LBL_MODULE_NAME' => 'Case File',
  'LBL_MODULE_TITLE' => 'Case File',
  'LBL_HOMEPAGE_TITLE' => 'My Case File',
  'LNK_NEW_RECORD' => 'Create Case File',
  'LNK_LIST' => 'View Case File',
  'LNK_IMPORT_G8R_GCASEFILE' => 'Import Case File',
  'LBL_SEARCH_FORM_TITLE' => 'Search Case File',
  'LBL_HISTORY_SUBPANEL_TITLE' => 'View History',
  'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Activities',
  'LBL_G8R_GCASEFILE_SUBPANEL_TITLE' => 'Case File',
  'LBL_NEW_FORM_TITLE' => 'New Case File',
  'LBL_DOCKET' => 'Docket:',
  'LBL_DATEFILED' => 'Date Filed:',
  'LBL_NOTIFCATIONDATE' => 'Notifcation Date:',
  'LBL_SOL' => 'SOL',
  'LBL_COURT_G8R_ORGANIZATIONS_ID' => 'Court (related  ID)',
  'LBL_COURT' => 'Court',
  'LBL_FEEARRANGEMENT' => 'Fee Arrangement',
  'LBL_CTYPE_G8R_CTYPE_ID' => 'Case Type (related  ID)',
  'LBL_CTYPE' => 'Case Type',
  'LBL_TAGS' => 'tags',
  'LBL_CASE_NUMBER' => 'Case Number',
);
